app_joboard_app_job:
    resource: "@AppJoboardBundle/Resources/config/routing/job.yml"
    prefix:   /job

app_joboard_homepage:
    path:     /hello/{name}
    defaults: { _controller: AppJoboardBundle:Default:index }

app_joboard_homepage:
    pattern:  /
    defaults: { _controller: AppJoboardBundle:Job:index }